<a href="https://colab.research.google.com/github/sushmitha4055/AI-CODING-4055-/blob/main/LAb_17_AI_AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Re-creating the sample employee dataset
data = {
    'employee_id': [101, 102, 103, 104, 105, 101, 106, 107, 108, 109],
    'salary': [60000, 75000, np.nan, 50000, 90000, 60000, 65000, 80000, np.nan, 70000],
    'designation': ['Software Engineer', 'Data Scientist', np.nan, 'Project Manager', 'Software Engineer', 'Software Engineer', 'HR Specialist', 'Data Scientist', 'Marketing Analyst', 'HR Specialist'],
    'experience': [3, 5, 2, np.nan, 7, 3, 4, 6, 1, 5],
    'employment_type': ['Full-time', 'Full-time', 'Contract', 'Full-time', 'Part-time', 'Full-time', 'Contract', 'Full-time', 'Part-time', 'Full-time']
}
df = pd.DataFrame(data)

print("Sample dataset recreated:")
display(df.head())

Sample dataset recreated:

   employee_id   salary        designation  experience employment_type
0          101  60000.0  Software Engineer         3.0       Full-time
1          102  75000.0     Data Scientist         5.0       Full-time
2          103      NaN                NaN         2.0        Contract
3          104  50000.0    Project Manager         NaN       Full-time
4          105  90000.0  Software Engineer         7.0       Part-time

In [ ]:
# 2. Handle missing values
# For numerical columns (salary, experience), fill with median
# For categorical column (designation), fill with mode
df['salary'] = df['salary'].fillna(df['salary'].median())
df['experience'] = df['experience'].fillna(df['experience'].median())
df['designation'] = df['designation'].fillna(df['designation'].mode()[0])

print("Dataset after handling missing values:")
display(df.head())
print("\n" + "="*30 + "\n")

# 3. Remove duplicate employee IDs
df.drop_duplicates(subset='employee_id', keep='first', inplace=True)

print("Dataset after removing duplicate employee IDs:")
display(df.head())
print("\n" + "="*30 + "\n")

# 4. Standardize text values (job titles in lowercase)
df['designation'] = df['designation'].str.lower()

print("Dataset after standardizing designation text:")
display(df.head())
print("\n" + "="*30 + "\n")

# 5. Encode categorical features (designation, employment_type)
df_encoded = pd.get_dummies(df, columns=['designation', 'employment_type'], drop_first=True)

print("Cleaned and Encoded Dataset (first 5 rows):")
display(df_encoded.head())
print("\n" + "="*30 + "\n")

print("Cleaning process complete. The 'df_encoded' DataFrame contains the clean and transformed data.")

Dataset after handling missing values:

   employee_id   salary        designation  experience employment_type
0          101  60000.0  Software Engineer         3.0       Full-time
1          102  75000.0     Data Scientist         5.0       Full-time
2          103  67500.0  Software Engineer         2.0        Contract
3          104  50000.0    Project Manager         4.0       Full-time
4          105  90000.0  Software Engineer         7.0       Part-time

==============================

Dataset after removing duplicate employee IDs:

   employee_id   salary        designation  experience employment_type
0          101  60000.0  Software Engineer         3.0       Full-time
1          102  75000.0     Data Scientist         5.0       Full-time
2          103  67500.0  Software Engineer         2.0        Contract
3          104  50000.0    Project Manager         4.0       Full-time
4          105  90000.0  Software Engineer         7.0       Part-time

==============================

Dataset after standardizing designation text:

   employee_id   salary        designation  experience employment_type
0          101  60000.0  software engineer         3.0       Full-time
1          102  75000.0     data scientist         5.0       Full-time
2          103  67500.0  software engineer         2.0        Contract
3          104  50000.0    project manager         4.0       Full-time
4          105  90000.0  software engineer         7.0       Part-time

==============================

Cleaned and Encoded Dataset (first 5 rows):

,employee_id,salary,experience,designation_hr specialist,designation_marketing analyst,designation_project manager,designation_software engineer,employment_type_Full-time,employment_type_Part-time
0,101,60000.0,3.0,False,False,False,True,True,False
1,102,75000.0,5.0,False,False,False,False,True,False
2,103,67500.0,2.0,False,False,False,True,False,False
3,104,50000.0,4.0,False,False,True,False,True,False
4,105,90000.0,7.0,False,False,False,True,False,True

==============================

Cleaning process complete. The 'df_encoded' DataFrame contains the clean and transformed data.

**Task 2 – Student Performance Data Preprocessing**
Task:
Preprocess student performance data using AI assistance.
Instructions:
• Convert exam_date column into datetime format
• Extract new features (month, semester, day)
• Normalize total_marks
• Detect and handle outliers in marks using IQR or Z-score
Expected Output:
A transformed dataset with time-based academic features and normalized
marks.

In [ ]:
import pandas as pd
import numpy as np

# Create a sample student performance dataset
data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'exam_date': ['2023-09-15', '2023-10-20', '2023-09-10', '2023-11-05', '2023-10-01', '2023-09-25', '2023-11-10', '2023-10-15', '2023-09-01', '2023-11-20'],
    'total_marks': [85, 72, 90, 68, 78, 92, 60, 88, 95, 75],
    'subject': ['Math', 'Science', 'Math', 'English', 'Science', 'Math', 'English', 'Science', 'Math', 'English'],
    'attendance': [95, 88, 98, 75, 90, 99, 70, 92, 97, 80]
}
df_student = pd.DataFrame(data)

print("Sample Student Performance Dataset:")
display(df_student.head())

# Placeholder to import your own dataset
# If you have a CSV file named 'student_data.csv', you can load it like this:
# df_student = pd.read_csv('student_data.csv')
# Ensure your dataset has 'exam_date' and 'total_marks' columns, and adjust other column names as needed.

print("\n" + "="*30 + "\n")

# 1. Convert exam_date column into datetime format
df_student['exam_date'] = pd.to_datetime(df_student['exam_date'])

print("Dataset after converting 'exam_date' to datetime:")
display(df_student.head())

# 2. Extract new features (month, semester, day)
df_student['exam_month'] = df_student['exam_date'].dt.month
df_student['exam_day'] = df_student['exam_date'].dt.day
# Assuming a simple semester division for demonstration: Sep-Dec is Fall (1), Jan-Aug is Spring/Summer (2)
df_student['semester'] = df_student['exam_month'].apply(lambda x: 1 if x >= 9 and x <= 12 else 2)

print("Dataset after extracting new date features:")
display(df_student.head())

# 3. Normalize total_marks (Min-Max Normalization)
min_marks = df_student['total_marks'].min()
max_marks = df_student['total_marks'].max()
df_student['normalized_marks'] = (df_student['total_marks'] - min_marks) / (max_marks - min_marks)

print("Dataset after normalizing 'total_marks':")
display(df_student.head())

# 4. Detect and handle outliers in marks using IQR
Q1 = df_student['total_marks'].quantile(0.25)
Q3 = df_student['total_marks'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identifying outliers
outliers = df_student[(df_student['total_marks'] < lower_bound) | (df_student['total_marks'] > upper_bound)]

print(f"\nDetected Outliers in total_marks (using IQR, if any):\n{outliers}")

# Handling outliers: Cap them at the bounds (you could also remove them or use other methods)
df_student['total_marks_handled'] = df_student['total_marks'].clip(lower=lower_bound, upper=upper_bound)

print("\nDataset after handling outliers in 'total_marks' (capped):")
display(df_student.head())

print("\n" + "="*30 + "\n")
print("Student performance data preprocessing complete.")

Sample Student Performance Dataset:

   student_id   exam_date  total_marks  subject  attendance
0           1  2023-09-15           85     Math          95
1           2  2023-10-20           72  Science          88
2           3  2023-09-10           90     Math          98
3           4  2023-11-05           68  English          75
4           5  2023-10-01           78  Science          90

==============================

Dataset after converting 'exam_date' to datetime:

   student_id  exam_date  total_marks  subject  attendance
0           1 2023-09-15           85     Math          95
1           2 2023-10-20           72  Science          88
2           3 2023-09-10           90     Math          98
3           4 2023-11-05           68  English          75
4           5 2023-10-01           78  Science          90

Dataset after extracting new date features:

,student_id,exam_date,total_marks,subject,attendance,exam_month,exam_day,semester
0,1,2023-09-15,85,Math,95,9,15,1
1,2,2023-10-20,72,Science,88,10,20,1
2,3,2023-09-10,90,Math,98,9,10,1
3,4,2023-11-05,68,English,75,11,5,1
4,5,2023-10-01,78,Science,90,10,1,1

Dataset after normalizing 'total_marks':

,student_id,exam_date,total_marks,subject,attendance,exam_month,exam_day,semester,normalized_marks
0,1,2023-09-15,85,Math,95,9,15,1,0.714286
1,2,2023-10-20,72,Science,88,10,20,1,0.342857
2,3,2023-09-10,90,Math,98,9,10,1,0.857143
3,4,2023-11-05,68,English,75,11,5,1,0.228571
4,5,2023-10-01,78,Science,90,10,1,1,0.514286

Detected Outliers in total_marks (using IQR, if any):
Empty DataFrame
Columns: [student_id, exam_date, total_marks, subject, attendance, exam_month, exam_day, semester, normalized_marks]
Index: []

Dataset after handling outliers in 'total_marks' (capped):

,student_id,exam_date,total_marks,subject,attendance,exam_month,exam_day,semester,normalized_marks,total_marks_handled
0,1,2023-09-15,85,Math,95,9,15,1,0.714286,85
1,2,2023-10-20,72,Science,88,10,20,1,0.342857,72
2,3,2023-09-10,90,Math,98,9,10,1,0.857143,90
3,4,2023-11-05,68,English,75,11,5,1,0.228571,68
4,5,2023-10-01,78,Science,90,10,1,1,0.514286,78

==============================

Student performance data preprocessing complete.

**Task 3 – Student Health Data Preparation**
Task:
Clean and preprocess student health records using AI scripts.
Instructions:
• Handle missing values in height, weight, BMI
• Encode categorical features (medical_condition, fitness_status)
• Scale numerical features using standard scaling
• Split dataset into training and testing sets
Expected Output:
A preprocessed dataset ready for predictive health analysis.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# 1. Create a sample student health dataset
data_health = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'height_cm': [170, 165, np.nan, 180, 175, 160, 172, 185, np.nan, 168],
    'weight_kg': [65, 58, 70, 75, np.nan, 55, 68, 80, 62, np.nan],
    'BMI': [22.5, 21.3, 23.8, np.nan, 24.5, 21.5, 23.0, 23.5, 22.0, 21.8],
    'medical_condition': ['None', 'Asthma', 'None', 'Allergies', 'None', 'Asthma', 'None', 'None', 'Allergies', 'None'],
    'fitness_status': ['Fit', 'Moderate', 'Fit', 'Fit', 'Low', 'Moderate', 'Fit', 'Fit', 'Low', 'Moderate']
}
df_health = pd.DataFrame(data_health)

print("Original Student Health Dataset:")
display(df_health.head())
print("\n" + "="*30 + "\n")

# Placeholder for importing your own dataset
# df_health = pd.read_csv('student_health_data.csv')

# Define numerical and categorical features
numerical_features = ['height_cm', 'weight_kg', 'BMI']
categorical_features = ['medical_condition', 'fitness_status']

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Combine preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Apply preprocessing to the dataset
df_processed = preprocessor.fit_transform(df_health)

# Get feature names for the processed DataFrame (optional, for better readability)
feature_names = numerical_features + \
                list(preprocessor.named_transformers_['cat']['onehot'].get_feature_names_out(categorical_features))

df_processed_df = pd.DataFrame(df_processed, columns=feature_names)

print("Processed Dataset (first 5 rows - after handling missing values, encoding, and scaling):")
display(df_processed_df.head())
print("\n" + "="*30 + "\n")

# 5. Split dataset into training and testing sets
# Assuming we want to predict a target variable, let's create a dummy target for demonstration
df_health['target'] = np.random.randint(0, 2, size=len(df_health)) # Dummy binary target

X = df_processed_df  # Features are the processed data
y = df_health['target'] # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

print("\n" + "="*30 + "\n")
print("Student health data preparation complete. The dataset is split into X_train, X_test, y_train, y_test.")

Original Student Health Dataset:

   student_id  height_cm  weight_kg   BMI medical_condition fitness_status
0           1      170.0       65.0  22.5              None            Fit
1           2      165.0       58.0  21.3            Asthma       Moderate
2           3        NaN       70.0  23.8              None            Fit
3           4      180.0       75.0   NaN         Allergies            Fit
4           5      175.0        NaN  24.5              None            Low

==============================

Processed Dataset (first 5 rows - after handling missing values, encoding, and scaling):

,height_cm,weight_kg,BMI,medical_condition_Allergies,medical_condition_Asthma,medical_condition_None,fitness_status_Fit,fitness_status_Low,fitness_status_Moderate
0,-0.251721,-0.227208,-0.140535,0.0,0.0,1.0,1.0,0.0,0.0
1,-0.992076,-1.221241,-1.345121,0.0,1.0,0.0,0.0,0.0,1.0
2,-0.103650,0.482816,1.164433,0.0,0.0,1.0,1.0,0.0,0.0
3,1.228989,1.192840,-0.140535,1.0,0.0,0.0,1.0,0.0,0.0
4,0.488634,-0.014200,1.867109,0.0,0.0,1.0,0.0,1.0,0.0

==============================

Shape of X_train: (8, 9)
Shape of X_test: (2, 9)
Shape of y_train: (8,)
Shape of y_test: (2,)

==============================

Student health data preparation complete. The dataset is split into X_train, X_test, y_train, y_test.

**Task 4: Real-Time Application: Ride-Sharing Data Cleaning**
Scenario:
A ride-sharing company has trip data with errors.
Requirements:
• Standardize pickup and drop locations
• Fill missing fare amounts with median values
• Remove duplicate ride entries
• Normalize driver ratings
• Generate a summary of data improvements
Expected Output:
A clean dataset ready for operational analysis.

In [ ]:
import pandas as pd
import numpy as np

# 1. Create a sample ride-sharing dataset
data_rides = {
    'ride_id': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    'pickup_location': [' Downtown  ', 'Airport', 'Suburb A', 'Downtown', '  City Center', 'Airport', 'Suburb B', 'Downtown', 'City Center  ', 'Suburb A'],
    'dropoff_location': ['Uptown', '  City Center', 'Downtown', 'Suburb A', 'Airport  ', 'Suburb B', 'Uptown', 'Airport', 'Downtown', 'City Center'],
    'fare_amount': [25.50, 45.00, np.nan, 20.00, 30.75, 48.20, 15.00, np.nan, 22.00, 35.50],
    'driver_rating': [4.8, 3.5, 5.0, 4.2, np.nan, 4.9, 3.0, 4.5, 4.0, 5.0],
    'ride_timestamp': ['2023-01-01 10:00:00', '2023-01-01 10:15:00', '2023-01-01 10:30:00', '2023-01-01 10:45:00', '2023-01-01 11:00:00',
                       '2023-01-01 10:15:00', '2023-01-01 11:30:00', '2023-01-01 11:45:00', '2023-01-01 12:00:00', '2023-01-01 12:15:00']
}
df_rides = pd.DataFrame(data_rides)

print("Original Ride-Sharing Dataset:")
display(df_rides.head())
print("\n" + "="*30 + "\n")

# Placeholder for importing your own dataset
# If you have a CSV file named 'ride_data.csv', you can load it like this:
# df_rides = pd.read_csv('ride_data.csv')
# Ensure your dataset has similar columns or adjust the code as needed.

# 2. Standardize pickup and drop locations
df_rides['pickup_location'] = df_rides['pickup_location'].str.strip().str.lower()
df_rides['dropoff_location'] = df_rides['dropoff_location'].str.strip().str.lower()

print("Dataset after standardizing locations:")
display(df_rides.head())
print("\n" + "="*30 + "\n")

# 3. Fill missing fare amounts with median values
df_rides['fare_amount'] = df_rides['fare_amount'].fillna(df_rides['fare_amount'].median())

print("Dataset after filling missing fare amounts:")
display(df_rides.head())
print("\n" + "="*30 + "\n")

# 4. Remove duplicate ride entries (assuming 'ride_id' and 'ride_timestamp' define a unique ride)
df_rides.drop_duplicates(subset=['ride_id', 'ride_timestamp'], inplace=True)

print("Dataset after removing duplicate ride entries:")
display(df_rides.head())
print("\n" + "="*30 + "\n")

# 5. Normalize driver ratings (Min-Max normalization)
# Handle potential NaN values in driver_rating before min/max calculation
df_rides['driver_rating_cleaned'] = df_rides['driver_rating'].fillna(df_rides['driver_rating'].median())
min_rating = df_rides['driver_rating_cleaned'].min()
max_rating = df_rides['driver_rating_cleaned'].max()
df_rides['normalized_driver_rating'] = (df_rides['driver_rating_cleaned'] - min_rating) / (max_rating - min_rating)

print("Dataset after normalizing driver ratings:")
display(df_rides.head())
print("\n" + "="*30 + "\n")

# 6. Generate a summary of data improvements
print("Summary of Data Improvements:")
print("- Standardized 'pickup_location' and 'dropoff_location' to lowercase and removed extra spaces.")
# Calculate how many NaNs were in original fare_amount to report
original_fare_nans = pd.Series(data_rides['fare_amount']).isnull().sum()
print(f"- Filled {original_fare_nans} missing 'fare_amount' values with the median.")
# Calculate how many duplicates were removed
original_rows = len(pd.DataFrame(data_rides))
duplicate_rows_before_drop = pd.DataFrame(data_rides).duplicated(subset=['ride_id', 'ride_timestamp']).sum()
print(f"- Removed {duplicate_rows_before_drop} duplicate ride entries based on 'ride_id' and 'ride_timestamp'.")
print("- Normalized 'driver_rating' using Min-Max scaling, after filling missing values with the median.")

print("\nRide-sharing data cleaning process complete. The 'df_rides' DataFrame contains the clean and transformed data.")

Original Ride-Sharing Dataset:

,ride_id,pickup_location,dropoff_location,fare_amount,driver_rating,ride_timestamp
0,1001,Downtown,Uptown,25.50,4.8,2023-01-01 10:00:00
1,1002,Airport,City Center,45.00,3.5,2023-01-01 10:15:00
2,1003,Suburb A,Downtown,NaN,5.0,2023-01-01 10:30:00
3,1004,Downtown,Suburb A,20.00,4.2,2023-01-01 10:45:00
4,1005,City Center,Airport,30.75,NaN,2023-01-01 11:00:00

==============================

Dataset after standardizing locations:

,ride_id,pickup_location,dropoff_location,fare_amount,driver_rating,ride_timestamp
0,1001,downtown,uptown,25.50,4.8,2023-01-01 10:00:00
1,1002,airport,city center,45.00,3.5,2023-01-01 10:15:00
2,1003,suburb a,downtown,NaN,5.0,2023-01-01 10:30:00
3,1004,downtown,suburb a,20.00,4.2,2023-01-01 10:45:00
4,1005,city center,airport,30.75,NaN,2023-01-01 11:00:00

==============================

Dataset after filling missing fare amounts:

,ride_id,pickup_location,dropoff_location,fare_amount,driver_rating,ride_timestamp
0,1001,downtown,uptown,25.500,4.8,2023-01-01 10:00:00
1,1002,airport,city center,45.000,3.5,2023-01-01 10:15:00
2,1003,suburb a,downtown,28.125,5.0,2023-01-01 10:30:00
3,1004,downtown,suburb a,20.000,4.2,2023-01-01 10:45:00
4,1005,city center,airport,30.750,NaN,2023-01-01 11:00:00

==============================

Dataset after removing duplicate ride entries:

,ride_id,pickup_location,dropoff_location,fare_amount,driver_rating,ride_timestamp
0,1001,downtown,uptown,25.500,4.8,2023-01-01 10:00:00
1,1002,airport,city center,45.000,3.5,2023-01-01 10:15:00
2,1003,suburb a,downtown,28.125,5.0,2023-01-01 10:30:00
3,1004,downtown,suburb a,20.000,4.2,2023-01-01 10:45:00
4,1005,city center,airport,30.750,NaN,2023-01-01 11:00:00

==============================

Dataset after normalizing driver ratings:

,ride_id,pickup_location,dropoff_location,fare_amount,driver_rating,ride_timestamp,driver_rating_cleaned,normalized_driver_rating
0,1001,downtown,uptown,25.500,4.8,2023-01-01 10:00:00,4.8,0.90
1,1002,airport,city center,45.000,3.5,2023-01-01 10:15:00,3.5,0.25
2,1003,suburb a,downtown,28.125,5.0,2023-01-01 10:30:00,5.0,1.00
3,1004,downtown,suburb a,20.000,4.2,2023-01-01 10:45:00,4.2,0.60
4,1005,city center,airport,30.750,NaN,2023-01-01 11:00:00,4.5,0.75

==============================

Summary of Data Improvements:
- Standardized 'pickup_location' and 'dropoff_location' to lowercase and removed extra spaces.
- Filled 2 missing 'fare_amount' values with the median.
- Removed 0 duplicate ride entries based on 'ride_id' and 'ride_timestamp'.
- Normalized 'driver_rating' using Min-Max scaling, after filling missing values with the median.

Ride-sharing data cleaning process complete. The 'df_rides' DataFrame contains the clean and transformed data.

In [ ]:
display(df_rides.describe(include='all'))

,ride_id,pickup_location,dropoff_location,fare_amount,driver_rating,ride_timestamp,driver_rating_cleaned,normalized_driver_rating
count,10.00000,10,10,10.000000,9.000000,10,10.00000,10.000000
unique,NaN,5,6,NaN,NaN,9,NaN,NaN
top,NaN,downtown,uptown,NaN,NaN,2023-01-01 10:15:00,NaN,NaN
freq,NaN,3,2,NaN,NaN,2,NaN,NaN
mean,1005.50000,NaN,NaN,29.820000,4.322222,NaN,4.34000,0.670000
std,3.02765,NaN,NaN,10.556776,0.712000,NaN,0.67363,0.336815
min,1001.00000,NaN,NaN,15.000000,3.000000,NaN,3.00000,0.000000
25%,1003.25000,NaN,NaN,22.875000,4.000000,NaN,4.05000,0.525000
50%,1005.50000,NaN,NaN,28.125000,4.500000,NaN,4.50000,0.750000
75%,1007.75000,NaN,NaN,34.312500,4.900000,NaN,4.87500,0.937500
max,1010.00000,NaN,NaN,48.200000,5.000000,NaN,5.00000,1.000000